### ISSUE TITLE
[Bug] Nothing added to the table sample exception to test the integration

### ISSUE THREAD

**Issue by CR1AT0RS** [rootstrap/exception_hunter#91]
Hey,

Can we please add some sample exceptions that you can generate from rails console to debug issues with exception_hunter? I have exception_hunter setup but I am not seeing any routes that show the exception_hunter UI and also database is empty although I have bunch of errors in my application. Is there a sample exception or something I can raise and see if it gets added in the datbase?

I am also getting no routes match:
http://localhost:3000/exception_hunter/errors
http://localhost:3000/admin/exception_hunter/errors
http://localhost:3000/admin/dashboard  - > blank 

I am not sure what the root cause is but I would appreciate some help on how to diagnose this issue.

**Comment by brunvez** [comment]
Hey @CR1AT0RS you should be able to see if ExceptionHunter is working by running `ExceptionHunter.track(new StandardError("Some error"))`. Although I do agree it'd be nice to add to the Readme, that and how to enable it on dev by changing the initializer.

**Comment by CR1AT0RS** [comment]
@brunvez Thanks Bruh brunvez 👯

**Comment by brunvez** [comment]
Thank _you_ for taking the time and testing the tool! I'd love to get your thoughts on it if you use it on staging or prod too!
