### ISSUE TITLE
Allow ignoring certain errors

### ISSUE THREAD

**Issue by brunvez** [rootstrap/exception_hunter#94]
#### Description

We should allow users to ignore certain errors if they occur too often and they will not be solved. In that case the exception will still be tracked but it would appear on a different tab, plus you wouldn't be notified.

#### Technical Requirements

As always implementations should avoid making DB migrations as much as possible. This particular feature can be implemented using the `status` column on the `ErrorGroup` model.

Since this also includes UI changes we have to make sure it still looks clean, especially since the tabs can get crowded.

**Comment by ajazfarhad** [comment]
Hi @brunvez ,  i'd like to work on this issue. Is it still available to work on.?

**Comment by brunvez** [comment]
Hey @ajazfarhad, sure thing feel free to make a PR for it, and don't hesitate to ping me if you need a hand!
